runtime: go122

env_variables:
  # Add your environment variables here
  # EXAMPLE_VAR: "value"

handlers:
  - url: /.*
    script: auto
    secure: always

manual_scaling:
  instances: 1

service: default
