runtime: go
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

env_variables:
  # Add your environment variables here
  # EXAMPLE_VAR: "value"

handlers:
  - url: /.*
    script: auto
    secure: always

manual_scaling:
  instances: 1

service: default
